name: release

permissions:
    contents: write

on:
    release:
        types:
            - created

jobs:
    release:
        runs-on: windows-latest
        defaults:
            run:
                shell: powershell
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: ilammy/msvc-dev-cmd@v1
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  targets: x86_64-unknown-linux-musl
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - run: ./download_and_build_lua.ps1
            - run: cargo build --release
            - run: cargo build --release --target x86_64-unknown-linux-musl --bin install
            - run: Move-Item build/lua54/lua54.dll ./lua54.dll
            - run: python make_dist.py
            - run: mv dist.zip chaudloader-${{ github.ref_name }}-windows.zip
            - run: mv dist.tar.bz2 chaudloader-${{ github.ref_name }}-linux.tar.bz2
            - uses: softprops/action-gh-release@v2
              with:
                  token: ${{ github.token }}
                  files: |
                    target/release/chaudloader.dll
                    chaudloader-${{ github.ref_name }}-windows.zip
                    chaudloader-${{ github.ref_name }}-linux.tar.bz2
